"""Datacard/shapes export and Combine execution (standalone container).

The combine container needs --cleanenv (drops the LCG PYTHONPATH), which also
drops the kerberos cache, making EOS read-only inside it. All combine steps
therefore run in a local scratch directory; results are copied back by the
host process.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

import numpy as np

from wham import __version__, util
from wham.config import AnalysisConfig
from wham.fitconfig import FitConfig, datacard_processes, syst_matches

SHAPES_FILE = "shapes.root"
DATACARD_FILE = "datacard.txt"
WORKSPACE_FILE = "workspace.root"
CP_MODEL_FILE = "cpmodel.py"
FITRESULT_FILE = "fitresult.json"
DUMP_SCRIPT_FILE = "dump_fitresult.py"

# uproot cannot read RooFitResult, so the postfit parameters (for the pulls
# plot) are dumped to JSON inside the container, where ROOT is available.
_DUMP_TEMPLATE = '''"""Generated by wham: dump fit_s floating parameters to JSON."""
import json

import ROOT

f = ROOT.TFile.Open("{fitdiag}")
res = f.Get("fit_s")
out = {{}}
if res:
    for p in res.floatParsFinal():
        out[p.GetName()] = {{"value": p.getVal(), "error": p.getError()}}
with open("{out}", "w") as fh:
    json.dump(out, fh, indent=1)
'''

# Custom physics model: multiSignalModel's expr:: maps don't promote the
# inner parameter to a POI, so we generate this explicit model instead.
_CP_MODEL_TEMPLATE = '''"""Generated by wham: CP mixing model, yields cos^2(alpha)*even + sin^2(alpha)*odd."""
from HiggsAnalysis.CombinedLimit.PhysicsModel import PhysicsModel


class CPMixing(PhysicsModel):
    def doParametersOfInterest(self):
        self.modelBuilder.doVar("alpha[{init},{lo},{hi}]")
        self.modelBuilder.factory_('expr::mu_even("cos(@0)*cos(@0)", alpha)')
        self.modelBuilder.factory_('expr::mu_odd("sin(@0)*sin(@0)", alpha)')
        self.modelBuilder.doSet("POI", "alpha")

    def getYieldScale(self, bin, process):
        if process == "{even}":
            return "mu_even"
        if process == "{odd}":
            return "mu_odd"
        return 1


cp_mixing = CPMixing()
'''


def dc_name(process: str) -> str:
    """Datacard-safe process name (combine chokes on '+' etc.)."""
    return "".join(c if (c.isalnum() or c == "_") else "_" for c in process)


def signal_region(cfg: AnalysisConfig) -> str:
    return "OS" if cfg.qcd.method == "ss" else "OS_iso"


# ------------------------------------------------------------- templates


def _slice1d(h: Any, process: str, region: str):
    return h[{"process": process, "region": region, "variation": "nominal"}].copy()


def _clip_negative(h1, label: str, console=None) -> None:
    view = h1.view()
    neg = view["value"] < 0
    if np.any(neg):
        if console is not None:
            console.print(f"  [yellow]clipped {int(neg.sum())} negative bins in {label}[/yellow]")
        view["value"][neg] = 0.0


def inject_toy_asymmetry(even_h, odd_h, asymmetry: float) -> None:
    """Modulate templates by (1 +- A*cos(x)) in place — yield-preserving toy."""
    centers = even_h.axes[0].centers
    for h1, sign in ((even_h, +1.0), (odd_h, -1.0)):
        view = h1.view()
        factor = 1.0 + sign * asymmetry * np.cos(centers)
        before = view["value"].sum()
        view["value"] *= factor
        view["variance"] *= factor**2
        after = view["value"].sum()
        if after > 0:
            view["value"] *= before / after
            view["variance"] *= (before / after) ** 2


def fit_templates(
    fit: FitConfig, cfg: AnalysisConfig, hists: dict, console=None
) -> tuple[dict[str, Any], list[str], list[str]]:
    """Build datacard templates.

    Returns (templates, signal_dc_names, background_dc_names); templates is
    {datacard_name: 1D hist}, including 'data_obs'. Zero-yield backgrounds
    are dropped.
    """
    region = signal_region(cfg)
    h_datamc = hists[("datamc", fit.variable)]
    signals, backgrounds = datacard_processes(fit, cfg)

    templates: dict[str, Any] = {}
    templates["data_obs"] = _slice1d(h_datamc, cfg.data_process(), region)

    kept_backgrounds: list[str] = []
    for proc in backgrounds:
        h1 = _slice1d(h_datamc, proc, region)
        _clip_negative(h1, proc, console)
        if h1.view()["value"].sum() <= 0:
            if console is not None:
                console.print(f"  [yellow]dropping zero-yield background '{proc}'[/yellow]")
            continue
        templates[dc_name(proc)] = h1
        kept_backgrounds.append(dc_name(proc))

    if fit.mode == "cp":
        h_fitcp = hists[("fitcp", fit.variable)]
        even = h_fitcp[{"process": fit.signal, "region": "even", "variation": "nominal"}].copy()
        odd = h_fitcp[{"process": fit.signal, "region": "odd", "variation": "nominal"}].copy()
        _clip_negative(even, f"{fit.signal} even", console)
        _clip_negative(odd, f"{fit.signal} odd", console)
        if fit.toy.asymmetry != 0.0:
            inject_toy_asymmetry(even, odd, fit.toy.asymmetry)
        templates[dc_name(signals[0])] = even
        templates[dc_name(signals[1])] = odd
    else:
        h1 = _slice1d(h_datamc, fit.signal, region)
        _clip_negative(h1, fit.signal, console)
        templates[dc_name(signals[0])] = h1

    return templates, [dc_name(s) for s in signals], kept_backgrounds


# ------------------------------------------------------------- writers


def write_shapes(path: Path, bin_name: str, templates: dict[str, Any]) -> None:
    import uproot

    with uproot.recreate(path) as f:
        for name, h1 in templates.items():
            clean = h1.copy()
            flow = clean.view(flow=True)
            for field in ("value", "variance"):
                flow[field][0] = 0.0
                flow[field][-1] = 0.0
            f[f"{bin_name}/{name}"] = clean


def write_datacard(
    path: Path,
    *,
    fit: FitConfig,
    bin_name: str,
    templates: dict[str, Any],
    signal_names: list[str],
    background_names: list[str],
    aliases: dict[str, str] | None = None,
) -> None:
    columns = signal_names + background_names  # datacard order: signals first
    # process ids: signals get 0, -1, ...; backgrounds 1..N
    ids = list(range(0, -len(signal_names), -1)) + list(range(1, len(background_names) + 1))
    rates = [templates[n].view()["value"].sum() for n in columns]
    observation = templates["data_obs"].view()["value"].sum()

    # systematic patterns are written against config process names; aliases
    # maps sanitized datacard names back (e.g. W_jets -> W+jets)
    parents = dict(aliases or {})
    if fit.mode == "cp":
        parents.update({n: fit.signal for n in signal_names})

    width = max(12, *(len(c) + 2 for c in columns))

    def row(label: str, kind: str, cells: list[str]) -> str:
        return f"{label:<22}{kind:<8}" + "".join(f"{c:<{width}}" for c in cells)

    lines = [
        f"# wham {__version__} | fit '{fit.name}' | mode {fit.mode} | variable {fit.variable}",
        "imax 1  number of categories",
        "jmax *  number of processes minus 1",
        "kmax *  number of nuisance parameters",
        "-" * 80,
        # NB: text2workspace substitutes $CHANNEL (not CombineHarvester's $BIN)
        f"shapes * {bin_name} {SHAPES_FILE} $CHANNEL/$PROCESS $CHANNEL/$PROCESS_$SYSTEMATIC",
        "-" * 80,
        f"bin          {bin_name}",
        f"observation  {observation:.4f}",
        "-" * 80,
        row("bin", "", [bin_name] * len(columns)),
        row("process", "", columns),
        row("process", "", [str(i) for i in ids]),
        row("rate", "", [f"{r:.4f}" for r in rates]),
        "-" * 80,
    ]

    for syst in fit.systematics:
        if syst.effect != "lnN":
            continue
        cells = [
            f"{syst.scaleFactor:g}" if syst_matches(syst.processes, name, parents.get(name))
            else "-"
            for name in columns
        ]
        lines.append(row(syst.name, syst.effect, cells))

    # rateParam: free normalization parameters, one line per matching process
    # (the shared name makes them one parameter in combine)
    for syst in fit.systematics:
        if syst.effect != "rateParam":
            continue
        bounds = f" [{syst.range[0]:g},{syst.range[1]:g}]" if syst.range else ""
        for name in columns:
            if syst_matches(syst.processes, name, parents.get(name)):
                lines.append(f"{syst.name} rateParam {bin_name} {name} {syst.init:g}{bounds}")

    if fit.auto_mc_stats is not None:
        lines.append(f"{bin_name} autoMCStats {fit.auto_mc_stats}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def export_key(fit: FitConfig, input_hist_keys: dict) -> str:
    return util.short_key(
        {
            "fit": fit.model_dump(mode="json"),
            "hists": {f"{f}/{n}": k for (f, n), k in sorted(input_hist_keys.items())},
            "version": __version__,
        }
    )


# ------------------------------------------------------------- container


def run_container(image: str, scratch: Path, command: str) -> str:
    """Run a command inside the combine container; returns combined output."""
    argv = [
        "apptainer", "exec", "--cleanenv",
        "--home", str(scratch), "--pwd", str(scratch),
        image, "bash", "-lc", command,
    ]
    result = subprocess.run(argv, capture_output=True, text=True, timeout=1800)
    output = result.stdout + result.stderr
    if result.returncode != 0:
        tail = "\n".join(output.splitlines()[-25:])
        raise RuntimeError(f"container command failed ({command!r}):\n{tail}")
    return output


def cp_model_source(fit: FitConfig, signal_names: list[str]) -> str:
    lo, hi = fit.scan_range()
    even, odd = signal_names
    return _CP_MODEL_TEMPLATE.format(init=0.5 * (lo + hi), lo=lo, hi=hi, even=even, odd=odd)


def dump_script_source(fit: FitConfig) -> str:
    return _DUMP_TEMPLATE.format(fitdiag=fitdiag_file(fit), out=FITRESULT_FILE)


def t2w_command(fit: FitConfig) -> str:
    if fit.mode == "rate":
        return f"text2workspace.py {DATACARD_FILE} -o {WORKSPACE_FILE}"
    # the generated model file sits next to the datacard in the scratch dir
    return (
        "PYTHONPATH=$PWD:$PYTHONPATH "
        f"text2workspace.py {DATACARD_FILE} -o {WORKSPACE_FILE} -P cpmodel:cp_mixing"
    )


def _common_fit_opts(fit: FitConfig) -> str:
    opts = []
    if fit.asimov.enabled:
        opts.append("-t -1")
        params = dict(fit.asimov.parameters)
        if fit.mode == "rate" and "r" not in params:
            params["r"] = 1.0
        if params:
            opts.append("--setParameters " + ",".join(f"{k}={v}" for k, v in params.items()))
    return " ".join(opts)


def fitdiag_command(fit: FitConfig) -> str:
    return (
        f"combine -M FitDiagnostics {WORKSPACE_FILE} -n .{fit.name} "
        f"--saveShapes --saveWithUncertainties {_common_fit_opts(fit)}"
    )


def scan_command(fit: FitConfig) -> str:
    lo, hi = fit.scan_range()
    return (
        f"combine -M MultiDimFit {WORKSPACE_FILE} -n .scan_{fit.name} "
        f"--algo grid --points {fit.scan.points} -P {fit.poi()} "
        f"--setParameterRanges {fit.poi()}={lo},{hi} --saveNLL "
        f"{_common_fit_opts(fit)}"
    )


# ------------------------------------------------------------- driver


def fitdiag_file(fit: FitConfig) -> str:
    return f"fitDiagnostics.{fit.name}.root"


def scan_file(fit: FitConfig) -> str:
    return f"higgsCombine.scan_{fit.name}.MultiDimFit.mH120.root"


def run_fit(
    fit: FitConfig,
    cfg: AnalysisConfig,
    hists: dict,
    input_hist_keys: dict,
    *,
    console=None,
    force: bool = False,
    datacard_only: bool = False,
) -> Path:
    """Export the datacard and run combine, skipping fresh stages.

    Returns the fit output directory.
    """
    fitdir = cfg.resolved_output_dir() / "fit" / fit.name
    fitdir.mkdir(parents=True, exist_ok=True)
    manifest_path = fitdir / "manifest.json"

    key = export_key(fit, input_hist_keys)
    old_key = None
    if manifest_path.is_file() and not force:
        try:
            old_key = json.loads(manifest_path.read_text()).get("export_key")
        except json.JSONDecodeError:
            old_key = None

    def missing(name: str) -> bool:
        return not (fitdir / name).is_file()

    stale = force or key != old_key
    do_export = stale or missing(DATACARD_FILE) or missing(SHAPES_FILE)
    do_t2w = do_export or missing(WORKSPACE_FILE)
    do_fitdiag = do_t2w or missing(fitdiag_file(fit))
    do_dump = do_fitdiag or missing(FITRESULT_FILE)
    do_scan = do_t2w or missing(scan_file(fit))

    templates, signal_names, background_names = fit_templates(fit, cfg, hists, console)

    if do_export:
        # the effective fit config — provenance, and a ready-to-edit starting
        # point for fits synthesized from a bare variable name
        import yaml

        (fitdir / "fitconfig.yaml").write_text(
            yaml.safe_dump(fit.model_dump(mode="json"), sort_keys=False),
            encoding="utf-8",
        )
        write_shapes(fitdir / SHAPES_FILE, fit.bin, templates)
        write_datacard(
            fitdir / DATACARD_FILE,
            fit=fit, bin_name=fit.bin, templates=templates,
            signal_names=signal_names, background_names=background_names,
            aliases={dc_name(p): p for p in cfg.stack_order()},
        )
        if fit.mode == "cp":
            (fitdir / CP_MODEL_FILE).write_text(
                cp_model_source(fit, signal_names), encoding="utf-8"
            )
        if console is not None:
            console.print(f"  [green]exported[/green] {fitdir / DATACARD_FILE}")
    elif console is not None:
        console.print("  datacard/shapes up to date")

    if datacard_only:
        manifest_path.write_text(json.dumps({"export_key": key, "time": time.time()}))
        return fitdir

    stages = [
        ("text2workspace", do_t2w, t2w_command(fit), [WORKSPACE_FILE]),
        ("FitDiagnostics", do_fitdiag, fitdiag_command(fit), [fitdiag_file(fit)]),
        ("fit result dump", do_dump, f"python3 {DUMP_SCRIPT_FILE}", [FITRESULT_FILE]),
        ("MultiDimFit scan", do_scan, scan_command(fit), [scan_file(fit)]),
    ]

    if any(run for _, run, _, _ in stages):
        # Scratch must be genuinely local: TMPDIR may point at EOS, which is
        # read-only inside the --cleanenv container (no kerberos cache).
        scratch = Path(tempfile.mkdtemp(prefix="wham_fit_", dir="/tmp"))
        log_lines: list[str] = []
        try:
            shutil.copy2(fitdir / DATACARD_FILE, scratch)
            shutil.copy2(fitdir / SHAPES_FILE, scratch)
            if fit.mode == "cp":
                # deterministic from the config; regenerate rather than copy
                (scratch / CP_MODEL_FILE).write_text(
                    cp_model_source(fit, signal_names), encoding="utf-8"
                )
            (scratch / DUMP_SCRIPT_FILE).write_text(dump_script_source(fit), encoding="utf-8")
            if not do_t2w and not missing(WORKSPACE_FILE):
                shutil.copy2(fitdir / WORKSPACE_FILE, scratch)
            if not do_fitdiag and not missing(fitdiag_file(fit)):
                shutil.copy2(fitdir / fitdiag_file(fit), scratch)

            for label, run, command, products in stages:
                if not run:
                    if console is not None:
                        console.print(f"  {label}: up to date")
                    continue
                t0 = time.perf_counter()
                log_lines.append(f"$ {command}")
                log_lines.append(run_container(fit.combine.image, scratch, command))
                for product in products:
                    shutil.copy2(scratch / product, fitdir / product)
                if console is not None:
                    console.print(
                        f"  [green]{label}[/green] done in {time.perf_counter() - t0:.1f}s"
                    )
        finally:
            (fitdir / "combine.log").write_text("\n".join(log_lines), encoding="utf-8")
            shutil.rmtree(scratch, ignore_errors=True)
    elif console is not None:
        console.print("  all combine stages up to date")

    manifest_path.write_text(json.dumps({"export_key": key, "time": time.time()}))
    return fitdir
