"""Datacard/shapes export, generated physics model, and Combine execution
(standalone container).

Everything is driven by the FitConfig: the model (POIs + per-template yield
scales) becomes a generated PhysicsModel, categories become datacard bins,
scans become MultiDimFit stages. The engine has no physics modes.

The combine container needs --cleanenv (drops the LCG PYTHONPATH), which also
drops the kerberos cache, making EOS read-only inside it. All combine steps
therefore run in a local scratch directory; results are copied back by the
host process.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

import numpy as np

from wham import __version__, util
from wham.config import AnalysisConfig
from wham.fitconfig import (
    FitConfig,
    ScanCfg,
    datacard_processes,
    dc_name,
    scale_map,
    syst_matches,
    template_parents,
    translate_formula,
)

SHAPES_FILE = "shapes.root"
DATACARD_FILE = "datacard.txt"
WORKSPACE_FILE = "workspace.root"
MODEL_FILE = "whammodel.py"
FITRESULT_FILE = "fitresult.json"
DUMP_SCRIPT_FILE = "dump_fitresult.py"

# The model is generated from the fit config: one doVar per POI, one
# expr:: per non-trivial yield scale, getYieldScale from a plain dict.
_MODEL_TEMPLATE = '''"""Generated by wham: physics model for fit '{name}'."""
from HiggsAnalysis.CombinedLimit.PhysicsModel import PhysicsModel

SCALES = {scales}


class WhamModel(PhysicsModel):
    def doParametersOfInterest(self):
{body}
        self.modelBuilder.doSet("POI", "{poi_set}")

    def getYieldScale(self, bin, process):
        return SCALES.get(process, 1)


wham_model = WhamModel()
'''

# uproot cannot read RooFitResult, so the postfit parameters and the
# covariance-approximation impacts (rho(poi, np) * sigma_poi) are dumped
# to JSON inside the container, where ROOT is available.
_DUMP_TEMPLATE = '''"""Generated by wham: dump fit_s parameters + POI impacts to JSON."""
import json

import ROOT

POIS = {pois}

f = ROOT.TFile.Open("{fitdiag}")
res = f.Get("fit_s")
out = {{"params": {{}}, "impacts": {{}}}}
if res:
    final = res.floatParsFinal()
    names = [final.at(i).GetName() for i in range(final.getSize())]
    for i in range(final.getSize()):
        p = final.at(i)
        out["params"][p.GetName()] = {{"value": p.getVal(), "error": p.getError()}}
    for poi in POIS:
        if poi not in names:
            continue
        sigma = out["params"][poi]["error"]
        out["impacts"][poi] = {{
            n: res.correlation(poi, n) * sigma for n in names if n != poi
        }}
with open("{out}", "w") as fh:
    json.dump(out, fh, indent=1)
'''


def signal_region(cfg: AnalysisConfig) -> str:
    return "OS" if cfg.qcd.method == "ss" else "OS_iso"


# ------------------------------------------------------------- generated code


def model_source(fit: FitConfig) -> str:
    pois = list(fit.model.pois)
    lines = []
    for poi, pcfg in fit.model.pois.items():
        lo, hi = pcfg.range
        lines.append(
            f'        self.modelBuilder.doVar("{poi}[{pcfg.init:g},{lo:g},{hi:g}]")'
        )
    scales: dict[str, str] = {}
    for template, expr in scale_map(fit).items():
        if expr.strip() in pois:  # bare POI: scale by the variable directly
            scales[template] = expr.strip()
            continue
        tformula, deps = translate_formula(expr, pois)
        scale_name = f"scale_{template}"
        lines.append(
            f"        self.modelBuilder.factory_("
            f"'expr::{scale_name}(\"{tformula}\", {', '.join(deps)})')"
        )
        scales[template] = scale_name
    return _MODEL_TEMPLATE.format(
        name=fit.name,
        scales=repr(scales),
        body="\n".join(lines),
        poi_set=",".join(pois),
    )


def dump_script_source(fit: FitConfig) -> str:
    return _DUMP_TEMPLATE.format(
        pois=repr(list(fit.model.pois)), fitdiag=fitdiag_file(fit), out=FITRESULT_FILE
    )


# ------------------------------------------------------------- templates


def _slice1d(h: Any, process: str, region: str):
    return h[{"process": process, "region": region, "variation": "nominal"}].copy()


def _clip_negative(h1, label: str, console=None) -> None:
    view = h1.view()
    neg = view["value"] < 0
    if np.any(neg):
        if console is not None:
            console.print(f"  [yellow]clipped {int(neg.sum())} negative bins in {label}[/yellow]")
        view["value"][neg] = 0.0


def inject_toy_asymmetry(first_h, second_h, asymmetry: float) -> None:
    """Modulate two templates by (1 +- A*cos(x)) in place — yield-preserving toy."""
    centers = first_h.axes[0].centers
    for h1, sign in ((first_h, +1.0), (second_h, -1.0)):
        view = h1.view()
        factor = 1.0 + sign * asymmetry * np.cos(centers)
        before = view["value"].sum()
        view["value"] *= factor
        view["variance"] *= factor**2
        after = view["value"].sum()
        if after > 0:
            view["value"] *= before / after
            view["variance"] *= (before / after) ** 2


def fit_templates(
    fit: FitConfig, cfg: AnalysisConfig, hists_by_cat: dict[str, dict], console=None
) -> tuple[dict[str, dict[str, Any]], list[str], list[str]]:
    """Build datacard templates for every category.

    Returns (templates, signal_names, background_names) where templates is
    {category: {datacard_name: 1D hist}} including 'data_obs'. Zero-yield
    backgrounds are dropped per category; background_names keeps the union.
    """
    region = signal_region(cfg)
    signal_names, backgrounds = datacard_processes(fit, cfg)

    templates: dict[str, dict[str, Any]] = {}
    for cat in fit.categories:
        hists = hists_by_cat[cat.name]
        h_datamc = hists[("datamc", cat.variable)]
        t: dict[str, Any] = {
            "data_obs": _slice1d(h_datamc, cfg.data_process(), region)
        }
        for proc in cfg.stack_order():
            pm = fit.model.processes.get(proc)
            if pm is None or pm.components is None:
                h1 = _slice1d(h_datamc, proc, region)
                _clip_negative(h1, f"{cat.name}/{proc}", console)
                if h1.view()["value"].sum() <= 0:
                    if pm is None:
                        if console is not None:
                            console.print(
                                f"  [yellow]dropping zero-yield background "
                                f"'{proc}' in '{cat.name}'[/yellow]"
                            )
                        continue
                    if console is not None:  # model process: keep, but warn
                        console.print(
                            f"  [yellow]model process '{proc}' has zero yield "
                            f"in '{cat.name}'[/yellow]"
                        )
                t[dc_name(proc)] = h1
            else:
                h_fitcp = hists[("fitcp", cat.variable)]
                comp_hists = []
                for comp in pm.components:
                    h1 = h_fitcp[
                        {"process": proc, "region": comp, "variation": "nominal"}
                    ].copy()
                    _clip_negative(h1, f"{cat.name}/{proc} {comp}", console)
                    comp_hists.append((comp, h1))
                if fit.toy.asymmetry != 0.0 and len(comp_hists) == 2:
                    inject_toy_asymmetry(comp_hists[0][1], comp_hists[1][1],
                                         fit.toy.asymmetry)
                for comp, h1 in comp_hists:
                    t[dc_name(f"{proc}_{comp}")] = h1
        templates[cat.name] = t

    cats = [c.name for c in fit.categories]
    background_names = [b for b in backgrounds if any(b in templates[c] for c in cats)]
    return templates, signal_names, background_names


# ------------------------------------------------------------- writers


def write_shapes(path: Path, templates: dict[str, dict[str, Any]]) -> None:
    import uproot

    with uproot.recreate(path) as f:
        for bin_name, by_name in templates.items():
            for name, h1 in by_name.items():
                clean = h1.copy()
                flow = clean.view(flow=True)
                for field in ("value", "variance"):
                    flow[field][0] = 0.0
                    flow[field][-1] = 0.0
                f[f"{bin_name}/{name}"] = clean


def write_datacard(
    path: Path,
    *,
    fit: FitConfig,
    templates: dict[str, dict[str, Any]],
    signal_names: list[str],
    background_names: list[str],
    parents: dict[str, str] | None = None,
) -> None:
    """Multi-bin datacard: one column per (category, process present there)."""
    parents = parents or {}
    cats = [c.name for c in fit.categories]
    order = signal_names + background_names
    # process ids: model templates get 0, -1, ...; backgrounds 1..N
    ids = {n: -i for i, n in enumerate(signal_names)}
    ids.update({n: i for i, n in enumerate(background_names, start=1)})

    columns = [(c, n) for c in cats for n in order if n in templates[c]]
    rates = [templates[c][n].view()["value"].sum() for c, n in columns]

    width = max(12, *(len(n) + 2 for _, n in columns), *(len(c) + 2 for c in cats))

    def row(label: str, kind: str, cells: list[str]) -> str:
        return f"{label:<22}{kind:<8}" + "".join(f"{c:<{width}}" for c in cells)

    def allowed(syst, cat: str) -> bool:
        return syst.categories is None or cat in syst.categories

    lines = [
        f"# wham {__version__} | fit '{fit.name}' | POIs {', '.join(fit.model.pois)}",
        f"imax {len(cats)}  number of categories",
        "jmax *  number of processes minus 1",
        "kmax *  number of nuisance parameters",
        "-" * 80,
        # NB: text2workspace substitutes $CHANNEL (not CombineHarvester's $BIN)
        f"shapes * * {SHAPES_FILE} $CHANNEL/$PROCESS $CHANNEL/$PROCESS_$SYSTEMATIC",
        "-" * 80,
        row("bin", "", cats),
        row("observation", "",
            [f"{templates[c]['data_obs'].view()['value'].sum():.4f}" for c in cats]),
        "-" * 80,
        row("bin", "", [c for c, _ in columns]),
        row("process", "", [n for _, n in columns]),
        row("process", "", [str(ids[n]) for _, n in columns]),
        row("rate", "", [f"{r:.4f}" for r in rates]),
        "-" * 80,
    ]

    for syst in fit.systematics:
        if syst.effect != "lnN":
            continue
        cells = [
            f"{syst.scaleFactor:g}"
            if allowed(syst, c) and syst_matches(syst.processes, n, parents.get(n))
            else "-"
            for c, n in columns
        ]
        lines.append(row(syst.name, syst.effect, cells))

    # rateParam: free normalization parameters, one line per matching
    # (bin, process); the shared name makes them one parameter in combine
    for syst in fit.systematics:
        if syst.effect != "rateParam":
            continue
        bounds = f" [{syst.range[0]:g},{syst.range[1]:g}]" if syst.range else ""
        for c, n in columns:
            if allowed(syst, c) and syst_matches(syst.processes, n, parents.get(n)):
                lines.append(f"{syst.name} rateParam {c} {n} {syst.init:g}{bounds}")

    if fit.auto_mc_stats is not None:
        lines.append(f"* autoMCStats {fit.auto_mc_stats}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def export_key(fit: FitConfig, input_hist_keys: dict) -> str:
    return util.short_key(
        {
            "fit": fit.model_dump(mode="json"),
            "hists": {"/".join(map(str, k)): v for k, v in sorted(input_hist_keys.items())},
            "version": __version__,
        }
    )


# ------------------------------------------------------------- container


def run_container(image: str, scratch: Path, command: str) -> str:
    """Run a command inside the combine container; returns combined output."""
    argv = [
        "apptainer", "exec", "--cleanenv",
        "--home", str(scratch), "--pwd", str(scratch),
        image, "bash", "-lc", command,
    ]
    result = subprocess.run(argv, capture_output=True, text=True, timeout=1800)
    output = result.stdout + result.stderr
    if result.returncode != 0:
        tail = "\n".join(output.splitlines()[-25:])
        raise RuntimeError(f"container command failed ({command!r}):\n{tail}")
    return output


def t2w_command(fit: FitConfig) -> str:
    # the generated model file sits next to the datacard in the scratch dir
    return (
        "PYTHONPATH=$PWD:$PYTHONPATH "
        f"text2workspace.py {DATACARD_FILE} -o {WORKSPACE_FILE} "
        f"-P {MODEL_FILE.removesuffix('.py')}:wham_model"
    )


def _common_fit_opts(fit: FitConfig) -> str:
    opts = []
    if fit.asimov.enabled:
        opts.append("-t -1")
        params = {p: cfg.init for p, cfg in fit.model.pois.items()}
        params.update(fit.asimov.parameters)
        opts.append("--setParameters " + ",".join(f"{k}={v:g}" for k, v in params.items()))
    return " ".join(opts)


def fitdiag_command(fit: FitConfig) -> str:
    return (
        f"combine -M FitDiagnostics {WORKSPACE_FILE} -n .{fit.name} "
        f"--saveShapes --saveWithUncertainties {_common_fit_opts(fit)}"
    )


def scan_tag(scan: ScanCfg) -> str:
    return "_".join(scan.pois)


def scan_window(
    fit: FitConfig, scan: ScanCfg, poi: str, index: int,
    fitresult: dict | None,
) -> tuple[float, float]:
    """Scan window for one POI: the explicit range/ranges entry if given,
    else best fit +- 10 sigma (clipped to the POI range) so the grid
    resolves the minimum, else the full POI range."""
    if len(scan.pois) == 1 and scan.range is not None:
        return scan.range
    if len(scan.pois) == 2 and scan.ranges is not None:
        return tuple(scan.ranges[index])
    lo, hi = fit.model.pois[poi].range
    params = (fitresult or {}).get("params", {})
    if poi in params and params[poi].get("error", 0) > 0:
        best, sigma = params[poi]["value"], params[poi]["error"]
        return max(lo, best - 10 * sigma), min(hi, best + 10 * sigma)
    return lo, hi


def scan_command(fit: FitConfig, scan: ScanCfg, fitresult: dict | None = None) -> str:
    ranges = [
        f"{poi}={lo:g},{hi:g}"
        for i, poi in enumerate(scan.pois)
        for lo, hi in [scan_window(fit, scan, poi, i, fitresult)]
    ]
    points = scan.points if len(scan.pois) == 1 else scan.points**2
    return (
        f"combine -M MultiDimFit {WORKSPACE_FILE} -n .scan_{fit.name}_{scan_tag(scan)} "
        f"--algo grid --points {points} "
        + " ".join(f"-P {p}" for p in scan.pois)
        + f" --setParameterRanges {':'.join(ranges)} --saveNLL "
        f"{_common_fit_opts(fit)}"
    )


# ------------------------------------------------------------- driver


def fitdiag_file(fit: FitConfig) -> str:
    return f"fitDiagnostics.{fit.name}.root"


def scan_file(fit: FitConfig, scan: ScanCfg) -> str:
    return f"higgsCombine.scan_{fit.name}_{scan_tag(scan)}.MultiDimFit.mH120.root"


def run_fit(
    fit: FitConfig,
    cfg: AnalysisConfig,
    hists_by_cat: dict[str, dict],
    input_hist_keys: dict,
    *,
    console=None,
    force: bool = False,
    datacard_only: bool = False,
) -> Path:
    """Export datacard/shapes/model and run combine, skipping fresh stages.

    Returns the fit output directory.
    """
    import yaml

    fitdir = cfg.resolved_output_dir() / "fit" / fit.name
    fitdir.mkdir(parents=True, exist_ok=True)
    manifest_path = fitdir / "manifest.json"

    key = export_key(fit, input_hist_keys)
    old_key = None
    if manifest_path.is_file() and not force:
        try:
            old_key = json.loads(manifest_path.read_text()).get("export_key")
        except json.JSONDecodeError:
            old_key = None

    def missing(name: str) -> bool:
        return not (fitdir / name).is_file()

    stale = force or key != old_key
    do_export = stale or missing(DATACARD_FILE) or missing(SHAPES_FILE) or missing(MODEL_FILE)
    do_t2w = do_export or missing(WORKSPACE_FILE)
    do_fitdiag = do_t2w or missing(fitdiag_file(fit))
    do_dump = do_fitdiag or missing(FITRESULT_FILE)
    scans = fit.resolved_scans()

    templates, signal_names, background_names = fit_templates(fit, cfg, hists_by_cat, console)

    if do_export:
        # the effective fit config — provenance and a ready-to-copy reference
        (fitdir / "fitconfig.yaml").write_text(
            yaml.safe_dump(fit.model_dump(mode="json"), sort_keys=False),
            encoding="utf-8",
        )
        write_shapes(fitdir / SHAPES_FILE, templates)
        write_datacard(
            fitdir / DATACARD_FILE,
            fit=fit, templates=templates,
            signal_names=signal_names, background_names=background_names,
            parents=template_parents(fit, cfg),
        )
        (fitdir / MODEL_FILE).write_text(model_source(fit), encoding="utf-8")
        if console is not None:
            console.print(f"  [green]exported[/green] {fitdir / DATACARD_FILE}")
    elif console is not None:
        console.print("  datacard/shapes up to date")

    if datacard_only:
        manifest_path.write_text(json.dumps({"export_key": key, "time": time.time()}))
        return fitdir

    def _fitresult() -> dict | None:
        # available to the scan stages: the dump stage runs (and is copied
        # back) before them, supplying best fit + sigma for auto-windowing
        try:
            return json.loads((fitdir / FITRESULT_FILE).read_text())
        except (OSError, json.JSONDecodeError):
            return None

    stages = [
        ("text2workspace", do_t2w, t2w_command(fit), [WORKSPACE_FILE]),
        ("FitDiagnostics", do_fitdiag, fitdiag_command(fit), [fitdiag_file(fit)]),
        ("fit result dump", do_dump, f"python3 {DUMP_SCRIPT_FILE}", [FITRESULT_FILE]),
        *(
            (f"MultiDimFit scan ({scan_tag(scan)})",
             do_t2w or do_dump or missing(scan_file(fit, scan)),
             lambda scan=scan: scan_command(fit, scan, _fitresult()),
             [scan_file(fit, scan)])
            for scan in scans
        ),
    ]

    if any(run for _, run, _, _ in stages):
        # Scratch must be genuinely local: TMPDIR may point at EOS, which is
        # read-only inside the --cleanenv container (no kerberos cache).
        scratch = Path(tempfile.mkdtemp(prefix="wham_fit_", dir="/tmp"))
        log_lines: list[str] = []
        try:
            shutil.copy2(fitdir / DATACARD_FILE, scratch)
            shutil.copy2(fitdir / SHAPES_FILE, scratch)
            # deterministic from the config; regenerate rather than copy
            (scratch / MODEL_FILE).write_text(model_source(fit), encoding="utf-8")
            (scratch / DUMP_SCRIPT_FILE).write_text(dump_script_source(fit), encoding="utf-8")
            if not do_t2w and not missing(WORKSPACE_FILE):
                shutil.copy2(fitdir / WORKSPACE_FILE, scratch)
            if not do_fitdiag and not missing(fitdiag_file(fit)):
                shutil.copy2(fitdir / fitdiag_file(fit), scratch)

            for label, run, command, products in stages:
                if not run:
                    if console is not None:
                        console.print(f"  {label}: up to date")
                    continue
                if callable(command):  # scan windows depend on the dump stage
                    command = command()
                t0 = time.perf_counter()
                log_lines.append(f"$ {command}")
                log_lines.append(run_container(fit.combine.image, scratch, command))
                for product in products:
                    shutil.copy2(scratch / product, fitdir / product)
                if console is not None:
                    console.print(
                        f"  [green]{label}[/green] done in {time.perf_counter() - t0:.1f}s"
                    )
        finally:
            (fitdir / "combine.log").write_text("\n".join(log_lines), encoding="utf-8")
            shutil.rmtree(scratch, ignore_errors=True)
    elif console is not None:
        console.print("  all combine stages up to date")

    manifest_path.write_text(json.dumps({"export_key": key, "time": time.time()}))
    return fitdir
